import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import type { Booking, BookingStatus } from '@/types/database';

interface CreateBookingData {
  package_id?: string;
  customer_name: string;
  customer_email: string;
  customer_phone: string;
  address_line1: string;
  address_line2?: string;
  city: string;
  pincode: string;
  floor_number?: number;
  property_sqft?: number;
  scheduled_date: string;
  scheduled_time: string;
  special_instructions?: string;
  base_price: number;
  addon_price?: number;
  total_price: number;
}

export function useBookings(filters?: { status?: BookingStatus; staffId?: string }) {
  return useQuery({
    queryKey: ['bookings', filters],
    queryFn: async () => {
      let query = supabase
        .from('bookings')
        .select(`
          *,
          package:packages(*, category:service_categories(*))
        `)
        .order('scheduled_date', { ascending: true });
      
      if (filters?.status) {
        query = query.eq('status', filters.status);
      }
      
      const { data, error } = await query;
      if (error) throw error;
      return data as Booking[];
    },
  });
}

export function useBooking(bookingId: string) {
  return useQuery({
    queryKey: ['booking', bookingId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('bookings')
        .select(`
          *,
          package:packages(*, category:service_categories(*))
        `)
        .eq('id', bookingId)
        .single();
      
      if (error) throw error;
      return data as Booking;
    },
    enabled: !!bookingId,
  });
}

export function useCreateBooking() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (data: CreateBookingData) => {
      const { data: booking, error } = await supabase
        .from('bookings')
        .insert({
          ...data,
          booking_number: '', // Will be generated by trigger
        })
        .select()
        .single();
      
      if (error) throw error;
      return booking as Booking;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bookings'] });
    },
  });
}

export function useUpdateBookingStatus() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async ({ bookingId, status }: { bookingId: string; status: BookingStatus }) => {
      const updateData: Record<string, unknown> = { status };
      if (status === 'completed') {
        updateData.completed_at = new Date().toISOString();
      }
      
      const { data, error } = await supabase
        .from('bookings')
        .update(updateData)
        .eq('id', bookingId)
        .select()
        .single();
      
      if (error) throw error;
      return data as Booking;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bookings'] });
    },
  });
}

export function useBookingByNumber(bookingNumber: string) {
  return useQuery({
    queryKey: ['booking-number', bookingNumber],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('bookings')
        .select(`
          *,
          package:packages(*, category:service_categories(*))
        `)
        .eq('booking_number', bookingNumber)
        .single();
      
      if (error) throw error;
      return data as Booking;
    },
    enabled: !!bookingNumber,
  });
}
