// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukeuvjnmkeuualdabscb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZXV2am5ta2V1dWFsZGFic2NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0ODU5NTAsImV4cCI6MjA4NjA2MTk1MH0.iDkwh7lWU_2WF5F51uqt8xG8UMZ3GwP9R3WZYj-geo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});